### ISSUE TITLE
提示not -filelist==。然后报错ResScanner Mission is failed

### ISSUE THREAD

**Issue by leozejia** [hxhb/ResScannerUE#1]
我只在Rules里面创建了一个规则，然后Save中给了一个存储路径，其他的都是默认的

**Comment by hxhb** [comment]
发一下具体的配置和运行Log.

**Comment by leozejia** [comment]
从右上角Export出来的配置：

{
	"configName": "Res_Check",
	"bByGlobalScanFilters": false,
	"bBlockRuleFilter": false,
	"globalScanFilters":
	{
		"filters": [
			{
				"path": "/Game"
			}
		],
		"assets": []
	},
	"globalIgnoreFilters":
	{
		"filters": [],
		"assets": []
	},
	"gitChecker":
	{
		"bGitCheck": false,
		"bRecordCommiter": false,
		"repoDir":
		{
			"path": "[PROJECT_CONTENT_DIR]"
		},
		"bDiffCommit": true,
		"beginCommitHash": "HEAD~",
		"endCommitHash": "HEAD",
		"bUncommitFiles": false
	},
	"bRuleWhiteList": false,
	"ruleWhileListIds": [],
	"bUseRulesTable": false,
	"importRulesTable": "None",
	"scannerRules": [
		{
			"ruleName": "TextureNameRule",
			"ruleDescribe": "检查贴图",
			"bEnableRule": true,
			"priority": "GENERAL",
			"bGlobalAssetMustMatchFilter": true,
			"scanFilters": [
				{
					"path": "/Game"
				}
			],
			"scanAssetType": "Class'/Script/Engine.Texture2D'",
			"recursiveClasses": true,
			"nameMatchRules":
			{
				"rules": [
					{
						"matchMode": "StartWith",
						"matchLogic": "Necessary",
						"rules": [
							{
								"ruleText": "T_",
								"bReverseCheck": false
							}
						]
					}
				],
				"bReverseCheck": false
			},
			"pathMatchRules":
			{
				"rules": [],
				"bReverseCheck": false
			},
			"propertyMatchRules":
			{
				"matchRules": [],
				"bReverseCheck": false
			},
			"customRules": [],
			"ignoreFilters":
			{
				"filters": [],
				"assets": []
			},
			"bEnablePostProcessor": false,
			"postProcessors": []
		}
	],
	"bSaveConfig": true,
	"bSaveResult": true,
	"bSavaeLiteResult": true,
	"savePath":
	{
		"path": "E:/_UnrealProjects/UnLua-2.1.2/UnLua-2.1.2/ResScanner"
	},
	"bStandaloneMode": true,
	"bNoShaderCompile": true,
	"additionalExecCommand": ""
}


Scan之后文件夹出现的config文件：

{
	"configName": "Res_Check",
	"bByGlobalScanFilters": false,
	"bBlockRuleFilter": false,
	"globalScanFilters":
	{
		"filters": [],
		"assets": []
	},
	"globalIgnoreFilters":
	{
		"filters": [],
		"assets": []
	},
	"gitChecker":
	{
		"bGitCheck": false,
		"bRecordCommiter": false,
		"repoDir":
		{
			"path": "[PROJECT_CONTENT_DIR]"
		},
		"bDiffCommit": true,
		"beginCommitHash": "HEAD~",
		"endCommitHash": "HEAD",
		"bUncommitFiles": false
	},
	"bRuleWhiteList": false,
	"ruleWhileListIds": [],
	"bUseRulesTable": false,
	"importRulesTable": "None",
	"scannerRules": [
		{
			"ruleName": "TextureNameRule",
			"ruleDescribe": "检查贴图",
			"bEnableRule": true,
			"priority": "GENERAL",
			"bGlobalAssetMustMatchFilter": true,
			"scanFilters": [
				{
					"path": "/Game"
				}
			],
			"scanAssetType": "Class'/Script/Engine.Texture2D'",
			"recursiveClasses": true,
			"nameMatchRules":
			{
				"rules": [
					{
						"matchMode": "StartWith",
						"matchLogic": "Necessary",
						"rules": [
							{
								"ruleText": "T_",
								"bReverseCheck": false
							}
						]
					}
				],
				"bReverseCheck": false
			},
			"pathMatchRules":
			{
				"rules": [],
				"bReverseCheck": false
			},
			"propertyMatchRules":
			{
				"matchRules": [],
				"bReverseCheck": false
			},
			"customRules": [],
			"ignoreFilters":
			{
				"filters": [],
				"assets": []
			},
			"bEnablePostProcessor": false,
			"postProcessors": []
		}
	],
	"bSaveConfig": true,
	"bSaveResult": true,
	"bSavaeLiteResult": true,
	"savePath":
	{
		"path": "E:/_UnrealProjects/UnLua-2.1.2/UnLua-2.1.2/ResScanner"
	},
	"bStandaloneMode": true,
	"bNoShaderCompile": true,
	"additionalExecCommand": ""
}


报错log：

LogTemp: ResScanner Res_Check Mission: D:/Program Files/Epic Games/UE_4.26/Engine/Binaries/Win64/UE4Editor-Cmd.exe "E:/_UnrealProjects/UnLua-2.1.2/UnLua-2.1.2/TPSProject.uproject" -run=ResScanner -config="E:/_UnrealProjects/UnLua-2.1.2/UnLua-2.1.2/Saved/ResScanner/ScannerConfig.json"  -NoShaderCompile -nullrhi
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:732][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'AllDesktop'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Android'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Android_ASTC'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Android_DXT'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Android_ETC2'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'AndroidClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Android_ASTCClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Android_DXTClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Android_ETC2Client'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Android_Multi'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:750][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Android_MultiClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:770][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'IOSClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:770][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'IOS'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:777][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Linux'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:784][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'LinuxNoEditor'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:791][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'LinuxClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:798][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'LinuxServer'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:806][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'LinuxAArch64NoEditor'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:814][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'LinuxAArch64Client'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:821][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'LinuxAArch64Server'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:841][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Lumin'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:841][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'LuminClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:848][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'MacNoEditor'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:855][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Mac'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:862][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'MacClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:869][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'MacServer'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:882][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'TVOSClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:882][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'TVOS'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:889][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'WindowsNoEditor'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:896][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'Windows'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:904][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'WindowsClient'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:911][  0]LogTargetPlatformManager: Display: Loaded TargetPlatform 'WindowsServer'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:911][  0]LogTargetPlatformManager: Display: Building Assets For Windows
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:918][  0]LogAudioDebug: Display: Lib vorbis DLL was dynamically loaded.
LogScannerNotificationProxy: Display: [2022.02.10-01.47.51:970][  0]LogDerivedDataCache: Display: Max Cache Size: 512 MB
LogScannerNotificationProxy: Display: [2022.02.10-01.47.52:014][  0]LogDerivedDataCache: Display: Loaded Boot cache: C:/Users/wuzj/AppData/Local/UnrealEngine/4.26/DerivedDataCache/Boot.ddc
LogScannerNotificationProxy: Display: [2022.02.10-01.47.52:027][  0]LogDerivedDataCache: Display: Pak cache opened for reading ../../../Engine/DerivedDataCache/Compressed.ddp.
LogScannerNotificationProxy: Display: [2022.02.10-01.47.52:034][  0]LogDerivedDataCache: Display: Performance to C:/Users/wuzj/AppData/Local/UnrealEngine/Common/DerivedDataCache: Latency=0.03ms. RandomReadSpeed=1679.65MBs, RandomWriteSpeed=165.41MBs. Assigned SpeedClass 'Local'
LogScannerNotificationProxy: Display: [2022.02.10-01.47.52:964][  0]LogAudioCaptureCore: Display: No Audio Capture implementations found. Audio input will be silent.
LogScannerNotificationProxy: Display: [2022.02.10-01.47.52:964][  0]LogAudioCaptureCore: Display: No Audio Capture implementations found. Audio input will be silent.
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:394][  0]LogResScannerCommandlet: Display: UResScannerCommandlet::Main
LogScannerNotificationProxy: Warning: 2.10-01.47.53:394][  0]LogResScannerCommandlet: Warning: not -filelist==.
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:583][  0]LogResScannerProxy: Display: {
LogScannerNotificationProxy: Display:     "configName": "Res_Check",
LogScannerNotificationProxy: Display:     "bByGlobalScanFilters": false,
LogScannerNotificationProxy: Display:     "bBlockRuleFilter": false,
LogScannerNotificationProxy: Display:     "globalScanFilters":
LogScannerNotificationProxy: Display:     {
LogScannerNotificationProxy: Display:         "filters": [],
LogScannerNotificationProxy: Display:         "assets": []
LogScannerNotificationProxy: Display:     },
LogScannerNotificationProxy: Display:     "globalIgnoreFilters":
LogScannerNotificationProxy: Display:     {
LogScannerNotificationProxy: Display:         "filters": [],
LogScannerNotificationProxy: Display:         "assets": []
LogScannerNotificationProxy: Display:     },
LogScannerNotificationProxy: Display:     "gitChecker":
LogScannerNotificationProxy: Display:     {
LogScannerNotificationProxy: Display:         "bGitCheck": false,
LogScannerNotificationProxy: Display:         "bRecordCommiter": false,
LogScannerNotificationProxy: Display:         "repoDir":
LogScannerNotificationProxy: Display:         {
LogScannerNotificationProxy: Display:             "path": "[PROJECT_CONTENT_DIR]"
LogScannerNotificationProxy: Display:         },
LogScannerNotificationProxy: Display:         "bDiffCommit": true,
LogScannerNotificationProxy: Display:         "beginCommitHash": "HEAD~",
LogScannerNotificationProxy: Display:         "endCommitHash": "HEAD",
LogScannerNotificationProxy: Display:         "bUncommitFiles": false
LogScannerNotificationProxy: Display:     },
LogScannerNotificationProxy: Display:     "bRuleWhiteList": false,
LogScannerNotificationProxy: Display:     "ruleWhileListIds": [],
LogScannerNotificationProxy: Display:     "bUseRulesTable": false,
LogScannerNotificationProxy: Display:     "importRulesTable": "None",
LogScannerNotificationProxy: Display:     "scannerRules": [
LogScannerNotificationProxy: Display:         {
LogScannerNotificationProxy: Display:             "ruleName": "TextureNameRule",
LogScannerNotificationProxy: Display:             "ruleDescribe": "????",
LogScannerNotificationProxy: Display:             "bEnableRule": true,
LogScannerNotificationProxy: Display:             "priority": "GENERAL",
LogScannerNotificationProxy: Display:             "bGlobalAssetMustMatchFilter": true,
LogScannerNotificationProxy: Display:             "scanFilters": [
LogScannerNotificationProxy: Display:                 {
LogScannerNotificationProxy: Display:                     "path": "/Game"
LogScannerNotificationProxy: Display:                 }
LogScannerNotificationProxy: Display:             ],
LogScannerNotificationProxy: Display:             "scanAssetType": "Class'/Script/Engine.Texture2D'",
LogScannerNotificationProxy: Display:             "recursiveClasses": true,
LogScannerNotificationProxy: Display:             "nameMatchRules":
LogScannerNotificationProxy: Display:             {
LogScannerNotificationProxy: Display:                 "rules": [
LogScannerNotificationProxy: Display:                     {
LogScannerNotificationProxy: Display:                         "matchMode": "StartWith",
LogScannerNotificationProxy: Display:                         "matchLogic": "Necessary",
LogScannerNotificationProxy: Display:                         "rules": [
LogScannerNotificationProxy: Display:                             {
LogScannerNotificationProxy: Display:                                 "ruleText": "T_",
LogScannerNotificationProxy: Display:                                 "bReverseCheck": false
LogScannerNotificationProxy: Display:                             }
LogScannerNotificationProxy: Display:                         ]
LogScannerNotificationProxy: Display:                     }
LogScannerNotificationProxy: Display:                 ],
LogScannerNotificationProxy: Display:                 "bReverseCheck": false
LogScannerNotificationProxy: Display:             },
LogScannerNotificationProxy: Display:             "pathMatchRules":
LogScannerNotificationProxy: Display:             {
LogScannerNotificationProxy: Display:                 "rules": [],
LogScannerNotificationProxy: Display:                 "bReverseCheck": false
LogScannerNotificationProxy: Display:             },
LogScannerNotificationProxy: Display:             "propertyMatchRules":
LogScannerNotificationProxy: Display:             {
LogScannerNotificationProxy: Display:                 "matchRules": [],
LogScannerNotificationProxy: Display:                 "bReverseCheck": false
LogScannerNotificationProxy: Display:             },
LogScannerNotificationProxy: Display:             "customRules": [],
LogScannerNotificationProxy: Display:             "ignoreFilters":
LogScannerNotificationProxy: Display:             {
LogScannerNotificationProxy: Display:                 "filters": [],
LogScannerNotificationProxy: Display:                 "assets": []
LogScannerNotificationProxy: Display:             },
LogScannerNotificationProxy: Display:             "bEnablePostProcessor": false,
LogScannerNotificationProxy: Display:             "postProcessors": []
LogScannerNotificationProxy: Display:         }
LogScannerNotificationProxy: Display:     ],
LogScannerNotificationProxy: Display:     "bSaveConfig": true,
LogScannerNotificationProxy: Display:     "bSaveResult": true,
LogScannerNotificationProxy: Display:     "bSavaeLiteResult": true,
LogScannerNotificationProxy: Display:     "savePath":
LogScannerNotificationProxy: Display:     {
LogScannerNotificationProxy: Display:         "path": "E:/_UnrealProjects/UnLua-2.1.2/UnLua-2.1.2/ResScanner"
LogScannerNotificationProxy: Display:     },
LogScannerNotificationProxy: Display:     "bStandaloneMode": true,
LogScannerNotificationProxy: Display:     "bNoShaderCompile": true,
LogScannerNotificationProxy: Display:     "additionalExecCommand": ""
LogScannerNotificationProxy: Display: }
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:584][  0]LogResScannerProxy: Display: RuleName TextureNameRule is Scanning.
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:584][  0]LogResScannerProxy: Display: RuleName TextureNameRule is Scanning. config:
LogScannerNotificationProxy: Display: {
LogScannerNotificationProxy: Display:     "ruleName": "TextureNameRule",
LogScannerNotificationProxy: Display:     "ruleDescribe": "????",
LogScannerNotificationProxy: Display:     "bEnableRule": true,
LogScannerNotificationProxy: Display:     "priority": "GENERAL",
LogScannerNotificationProxy: Display:     "bGlobalAssetMustMatchFilter": true,
LogScannerNotificationProxy: Display:     "scanFilters": [
LogScannerNotificationProxy: Display:         {
LogScannerNotificationProxy: Display:             "path": "/Game"
LogScannerNotificationProxy: Display:         }
LogScannerNotificationProxy: Display:     ],
LogScannerNotificationProxy: Display:     "scanAssetType": "Class'/Script/Engine.Texture2D'",
LogScannerNotificationProxy: Display:     "recursiveClasses": true,
LogScannerNotificationProxy: Display:     "nameMatchRules":
LogScannerNotificationProxy: Display:     {
LogScannerNotificationProxy: Display:         "rules": [
LogScannerNotificationProxy: Display:             {
LogScannerNotificationProxy: Display:                 "matchMode": "StartWith",
LogScannerNotificationProxy: Display:                 "matchLogic": "Necessary",
LogScannerNotificationProxy: Display:                 "rules": [
LogScannerNotificationProxy: Display:                     {
LogScannerNotificationProxy: Display:                         "ruleText": "T_",
LogScannerNotificationProxy: Display:                         "bReverseCheck": false
LogScannerNotificationProxy: Display:                     }
LogScannerNotificationProxy: Display:                 ]
LogScannerNotificationProxy: Display:             }
LogScannerNotificationProxy: Display:         ],
LogScannerNotificationProxy: Display:         "bReverseCheck": false
LogScannerNotificationProxy: Display:     },
LogScannerNotificationProxy: Display:     "pathMatchRules":
LogScannerNotificationProxy: Display:     {
LogScannerNotificationProxy: Display:         "rules": [],
LogScannerNotificationProxy: Display:         "bReverseCheck": false
LogScannerNotificationProxy: Display:     },
LogScannerNotificationProxy: Display:     "propertyMatchRules":
LogScannerNotificationProxy: Display:     {
LogScannerNotificationProxy: Display:         "matchRules": [],
LogScannerNotificationProxy: Display:         "bReverseCheck": false
LogScannerNotificationProxy: Display:     },
LogScannerNotificationProxy: Display:     "customRules": [],
LogScannerNotificationProxy: Display:     "ignoreFilters":
LogScannerNotificationProxy: Display:     {
LogScannerNotificationProxy: Display:         "filters": [],
LogScannerNotificationProxy: Display:         "assets": []
LogScannerNotificationProxy: Display:     },
LogScannerNotificationProxy: Display:     "bEnablePostProcessor": false,
LogScannerNotificationProxy: Display:     "postProcessors": []
LogScannerNotificationProxy: Display: }
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:586][  0]LogResScannerProxy: Display:  Texture2D /Game/AnimationAssets/UE4_Mannequin/Materials/MaterialLayers/T_ML_Aluminum01.T_ML_Aluminum01 match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:586][  0]LogResScannerProxy: Display:  Texture2D /Game/AnimationAssets/UE4_Mannequin/Materials/MaterialLayers/T_ML_Aluminum01_N.T_ML_Aluminum01_N match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:586][  0]LogResScannerProxy: Display:  Texture2D /Game/AnimationAssets/UE4_Mannequin/Materials/MaterialLayers/T_ML_Rubber_Blue_01_D.T_ML_Rubber_Blue_01_D match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:586][  0]LogResScannerProxy: Display:  Texture2D /Game/AnimationAssets/UE4_Mannequin/Materials/MaterialLayers/T_ML_Rubber_Blue_01_N.T_ML_Rubber_Blue_01_N match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:587][  0]LogResScannerProxy: Display:  Texture2D /Game/AnimationAssets/UE4_Mannequin/Textures/UE4Man_Logo_N.UE4Man_Logo_N match status is FALSE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:587][  0]LogResScannerProxy: Display:  Texture2D /Game/AnimationAssets/UE4_Mannequin/Textures/UE4_LOGO_CARD.UE4_LOGO_CARD match status is FALSE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:587][  0]LogResScannerProxy: Display:  Texture2D /Game/AnimationAssets/UE4_Mannequin/Textures/UE4_Mannequin_MAT_MASKA.UE4_Mannequin_MAT_MASKA match status is FALSE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:587][  0]LogResScannerProxy: Display:  Texture2D /Game/AnimationAssets/UE4_Mannequin/Textures/UE4_Mannequin_occlusion_Mobile.UE4_Mannequin_occlusion_Mobile match status is FALSE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:587][  0]LogResScannerProxy: Display:  Texture2D /Game/AnimationAssets/UE4_Mannequin/Textures/UE4_Mannequin__normals.UE4_Mannequin__normals match status is FALSE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:587][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Materials/MaterialLayers/T_ML_Aluminum01.T_ML_Aluminum01 match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:588][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Materials/MaterialLayers/T_ML_Aluminum01_N.T_ML_Aluminum01_N match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:588][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Materials/MaterialLayers/T_ML_FineRubber.T_ML_FineRubber match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:588][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Materials/MaterialLayers/T_ML_Rubber_Blue_01_D.T_ML_Rubber_Blue_01_D match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:588][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Materials/MaterialLayers/T_ML_Rubber_Blue_01_N.T_ML_Rubber_Blue_01_N match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:588][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Textures/T_FPGun_AO.T_FPGun_AO match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:588][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Textures/T_FPGun_M.T_FPGun_M match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:588][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Textures/T_FPGun_N.T_FPGun_N match status is TRUE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:588][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Textures/UE4_LOGO_CARD.UE4_LOGO_CARD match status is FALSE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:588][  0]LogResScannerProxy: Display:  Texture2D /Game/FPWeapon/Textures/UE4_Mannequin_occlusion_Mobile.UE4_Mannequin_occlusion_Mobile match status is FALSE!
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:590][  0]LogResScannerCommandlet: Display:
LogScannerNotificationProxy: Display: Asset Scan Result:
LogScannerNotificationProxy: Display: -------------------------------------------
LogScannerNotificationProxy: Display: ???: TextureNameRule (12) (????)
LogScannerNotificationProxy: Display:     /Game/AnimationAssets/UE4_Mannequin/Materials/MaterialLayers/T_ML_Aluminum01
LogScannerNotificationProxy: Display:     /Game/AnimationAssets/UE4_Mannequin/Materials/MaterialLayers/T_ML_Aluminum01_N
LogScannerNotificationProxy: Display:     /Game/AnimationAssets/UE4_Mannequin/Materials/MaterialLayers/T_ML_Rubber_Blue_01_D
LogScannerNotificationProxy: Display:     /Game/AnimationAssets/UE4_Mannequin/Materials/MaterialLayers/T_ML_Rubber_Blue_01_N
LogScannerNotificationProxy: Display:     /Game/FPWeapon/Materials/MaterialLayers/T_ML_Aluminum01
LogScannerNotificationProxy: Display:     /Game/FPWeapon/Materials/MaterialLayers/T_ML_Aluminum01_N
LogScannerNotificationProxy: Display:     /Game/FPWeapon/Materials/MaterialLayers/T_ML_FineRubber
LogScannerNotificationProxy: Display:     /Game/FPWeapon/Materials/MaterialLayers/T_ML_Rubber_Blue_01_D
LogScannerNotificationProxy: Display:     /Game/FPWeapon/Materials/MaterialLayers/T_ML_Rubber_Blue_01_N
LogScannerNotificationProxy: Display:     /Game/FPWeapon/Textures/T_FPGun_AO
LogScannerNotificationProxy: Display:     /Game/FPWeapon/Textures/T_FPGun_M
LogScannerNotificationProxy: Display:     /Game/FPWeapon/Textures/T_FPGun_N
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:590][  0]LogInit: Display:
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:590][  0]LogInit: Display: Warning/Error Summary (Unique only)
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:590][  0]LogInit: Display: -----------------------------------
LogScannerNotificationProxy: Warning:  LogResScannerCommandlet: Warning: not -filelist==.
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:591][  0]LogInit: Display:
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:591][  0]LogInit: Display: Commandlet->Main return this error code: -1
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:591][  0]LogInit: Display: With 0 error(s), 1 warning(s)
LogScannerNotificationProxy: Display: [2022.02.10-01.47.53:591][  0]LogInit: Display:
LogScannerNotificationProxy: Display: Execution of commandlet took:  0.20 seconds
LogScannerNotificationProxy: Display: [2022.02.10-01.47.54:065][  0]LogHttp: Display: cleaning up 0 outstanding Http requests.
LogScannerNotificationProxy: Error: The ResScanner Mission is faild.

**Comment by hxhb** [comment]
这是因为命中了你创建的规则，是正常的。
