### ISSUE TITLE
导入插件 找不到插件位置

### ISSUE THREAD

**Issue by shaomluo** [hxhb/ResScannerUE#2]
![image](https://user-images.githubusercontent.com/40687507/163697070-b8272f58-3243-4375-89c5-ee48c8ebf230.png)
![image](https://user-images.githubusercontent.com/40687507/163697087-b600f84a-af71-4f10-a4b0-2823c3ddd882.png)

请问楼主，我要打开如下插件界面 该怎么打开呢？
![image](https://user-images.githubusercontent.com/40687507/163697097-4fd0b847-ce5a-47c1-aab6-fc8936aca9d1.png)

**Comment by shaomluo** [comment]
求解决

**Comment by hxhb** [comment]
![image](https://user-images.githubusercontent.com/12034244/167814603-2a775025-877c-4cc8-8c2b-9124f242a57c.png)
这里展开。
